### ISSUE TITLE
Some `Arc`ed buffer for parallel (but disjoint) IO?

### ISSUE THREAD

**Issue by dpc** [tokio-rs/tokio-uring#103]
I'm trying to figure out how can I have a one big `Vec<u8>`-like buffer that I could `split` into disjoint parts and have parallel uring operations on each part. From what I can tell right now `slice` consumes the `Vec` so this will not work.

I guess this might require some `Arc`-like functionality, where I could hand over `Vec` to the runtime, get a slice for `buf[..]`, and then be able to call `slice.split(index)` to split the slice? Under the hood runtime would keep track of how many slices were handed over, and calling some `slice.into_inner()` on the last one would get the original `Vec` back?

I will have to do without it for now, but I think it's a useful use case to consider when designing the API.

**Comment by Noah-Kennedy** [comment]
This sounds like what the `bytes` crate is for. You can split and unsplit `bytes` objects.

**Comment by dpc** [comment]
Should  `tokio-uring` support it then? Or does it already and I missed it somewhere?

**Comment by Noah-Kennedy** [comment]
It does support it.
