### ISSUE TITLE
io_uring setup parameters

### ISSUE THREAD

**Issue by FrankReh** [tokio-rs/tokio-uring#105]
Currently, tokio_uring::start calls runtime::Runtime::new which calls the io_uring::IoUring::new with an entries count value of 256. But there are many settings besides the entries value that one may want to set when creating the kernel io_uring device.

The io_uring crate provides a builder API for setting those parameters that then get passed to the kernel's io_uring setup; but there is no API in tokio_uring to use that builder API for the parameters.

How should the tokio_uring support use of the io_uring builder api for setup parameters?

Can it reexport the io-uring Builder and pass that to another version of the tokio_uring::start (perhaps start_builder(b: io_uring::Builder)? Or should it make its own Builder that copies all the methods from the io-uring Builder, or should it provide a few mixes of parameter settings that are thought to be more safe or more tested or more useful than the rest?

**Comment by FrankReh** [comment]
Now with 0.5.5 of the io-uring, there are new ring sizes also, allowing for NVMe passthrough commands, for 5.19+ kernels.

**Comment by FrankReh** [comment]
@Noah-Kennedy I had thought about making the driver generic around the two traits created by io-uring 0.5.5 like so.

```rust
scoped_thread_local!(pub(crate) static CURRENT: Rc<RefCell<Inner<squeue::EntryMarker, cqueue::EntryMarker>>>);
```

But of course it's not that easy. The compiler wants a fixed size here, and the use of traits means the size isn't known at compile time.

So maybe we want to live with the driver used by this crate being the original sized Uring, and not plan on supporting the NVMe passthrough commands with it. The NVMe passthrough commands could be supported with an additional uring.

**Comment by Noah-Kennedy** [comment]
I'm going to read up on NVMe passthrough tonight, as I'm not as familiar with that aspect yet.
