### ISSUE TITLE
Add `custom_flags` to OpenOptions

### ISSUE THREAD

**Issue by ileixe** [tokio-rs/tokio-uring#108]
I'd like to open my device with `custom_flags` as our device requires O_NONBLOCK flag. Is it reasonable to add the field that user can touch it? (I wonder why it have not existed in the first place.)

If then, I will make a small PR to do.

**Comment by Noah-Kennedy** [comment]
Yeah, I'd say it's reasonable to add something akin to this: https://docs.rs/tokio/latest/tokio/fs/struct.OpenOptions.html#method.custom_flags
