### ISSUE TITLE
How is wrk-bench example meant to be exercised?

### ISSUE THREAD

**Issue by FrankReh** [tokio-rs/tokio-uring#114]
https://github.com/tokio-rs/tokio-uring/blob/master/examples/wrk-bench.rs is the program for running a TCP server that is running 16 accepts on the same socket. How is it meant to be exercised from a client? Is there a program for already doing this?

Thanks.

**Comment by Noah-Kennedy** [comment]
This is a stupid, silly benchmark I wrote that is intended to be used in conjunction with (wrk)[https://github.com/wg/wrk] or (rewrk)[https://github.com/lnx-search/rewrk].

This is really only intended for internal use when developing on this repo. It's useful for examining how different tweaks improve or worsen our throughput with a large volume of relatively small IO ops.

**Comment by FrankReh** [comment]
Thanks for the info. I've been working with my own fork of rewrk to stress the wrk-bench and a new wrk-bench-multishot. I added an HdrHistogram to show all the connection latencies. One day, we should have a rewrk that is based on tokio-uring too.
