### ISSUE TITLE
problem with explicit_close test

### ISSUE THREAD

**Issue by FrankReh** [tokio-rs/tokio-uring#119]
The explicit_close test sometimes fails because by the time it asserts the raw fd it is left holding is no longer valid, the kernel has opened a new file for one of the other tests and reused the raw fd value; so the raw fd is valid after all, just for a different file.

Not sure yet the best way to work around this race between one test and the other tests.

Manually, it is possible to run them with a single thread and then this test passes without any modifications.
```
cargo test --test fs_file -- --test-threads=1
```

Found an env variable can be set in .config/cargo.toml for the local project and with that the test threads can be set to 1.
Will send a PR when the existing PR is resolved.

**Comment by nik9000** [comment]
> cargo test --test fs_file -- --test-threads=1

:+1: If I run this in a while loop for a few minute it passes every time for me.
