### ISSUE TITLE
`driver::op::submit_with()` panic

### ISSUE THREAD

**Issue by ollie-etl** [tokio-rs/tokio-uring#145]
Pr #144 can trigger [This panic](https://github.com/tokio-rs/tokio-uring/blob/7adeacb88ce6fb93ce17645de1d2040ba50a36e5/src/driver/op.rs#L84-L86).

It can be reliably triggered if:
  - The concurrency factor submitting operations is greater than the submission queue size.
  - `.setup_sqpoll()` is specified on the ring builder

I speculate this can occur under other conditions, but the above is an easy way to fill the submission queue without draining it (i.e, if the ring poll thread is not scheduled whilst simultaneously having loads of things adding entries)

**Comment by FrankReh** [comment]
> * `.setup_sqpoll()` is specified on the ring builder

Oh, you are already running with squill.  Very interesting. I haven't tried that and have no idea what problems you may be running into there. Well I guess with the commit from yesterday it's working for you. I wonder if you have something trying to call tick periodically to try and keep up with the kernel's results or if tick is only being called when the thread is about to park itself?
