### ISSUE TITLE
bug: Calling `block_on` twice causes a panic

### ISSUE THREAD

**Issue by ollie-etl** [tokio-rs/tokio-uring#160]
See PR #159 for reproduction. I believe this was introduced bus was introduced in #142. It became possible to exercise it because of #148

**Comment by Noah-Kennedy** [comment]
The core issue here is that the background task for the driver is spawned in each block_on call.

**Comment by Noah-Kennedy** [comment]
I'll get to this tonight.

**Comment by Noah-Kennedy** [comment]
Fixed by #162.
