### ISSUE TITLE
DPDK support?

### ISSUE THREAD

**Issue by chenyuanrun** [tokio-rs/tokio-uring#276]
I'm doing a tokio-uring inspired, tokio based DPDK runtime, and I found many similarities between iouring and dpdk, are there any plan to integrate dpdk in tokio-uring in the future?

**Comment by chenyuanrun** [comment]
For DPDK we need userspace tcp/ip network stack, nvme driver and filesystem, that would be a hard work.

**Comment by Noah-Kennedy** [comment]
There are no plans to do so in tokio-uring. I'll close this as wontfix to reduce noise, but we can keep the discussion going in here.

**Comment by Noah-Kennedy** [comment]
What's your use case with this and DPDK?

**Comment by chenyuanrun** [comment]
> What's your use case with this and DPDK?

A super fast network/storage framework with super low latency. io-uring is good, but for ultra-high performance applications, dpdk could do better, with zero-copy memory and kernel-bypass stack.

I think dpdk, io-uring and the classic posix event loop (epoll) could run in the same runtime side by side, we just need a polling driver to prevent tokio from sleeping while polling dpdk resources.

**Comment by Noah-Kennedy** [comment]
@chenyuanrun can you file an issue in the main tokio repo? That would be the better place to handle discussions around DPDK.
