### ISSUE TITLE
[Bug] Wrong `Slice::deref/deref_mut` implementation

### ISSUE THREAD

**Issue by songzhi** [tokio-rs/tokio-uring#45]
Here's a minimal reproducible example:
```rust
let v = Vec::with_capacity(32);
let slice = v.slice(..);
let x = &*slice;
// raise error 'range end index 32 out of range for slice of length 0'
```

The reason is that `Slice` creation uses `bytes_total()`, `Slice::deref` uses `bytes_init()`.
The module level `deref/deref_mut` or the `Slice::deref/deref_mut` implementation, I'm not sure which one should be modified.

https://github.com/tokio-rs/tokio-uring/blob/2c9fbeab9694b74a21588ff398767ee8b5619032/src/buf/io_buf.rs#L79-L83
https://github.com/tokio-rs/tokio-uring/blob/2c9fbeab9694b74a21588ff398767ee8b5619032/src/buf/mod.rs#L16-L20
https://github.com/tokio-rs/tokio-uring/blob/2c9fbeab9694b74a21588ff398767ee8b5619032/src/buf/slice.rs#L126-L132

**Comment by mzabaluev** [comment]
#52 fixes this; the `Deref`/`DerefMut` impls should not try to extend the slice past the initialized part of the buffer. The helpers at the root of the `buf` module do the right thing.
