### ISSUE TITLE
How to combine the multi-thread mode of Tokio

### ISSUE THREAD

**Issue by silence-coding** [tokio-rs/tokio-uring#47]
Tokio-uring uses a single thread. If I want to use hyper and tokio-uring to implement a file server service, how to combine tokio's multi-thread runtime to improve the overall QPS?

**Comment by songzhi** [comment]
The normal way is using message passing instead of direct function calls. You can learn about actor model, [actix](https://actix.rs/) is a good framework using it. Here's a simple example showing how the message passing works:
```rust
use std::rc::Rc;
use tokio::sync::{mpsc, oneshot};
use tokio::task::LocalSet;

#[derive(Debug)]
pub struct UringRequest {
    tx: oneshot::Sender<UringResponse>,
}

#[derive(Debug)]
pub struct UringResponse {}

struct Uring {
    field1: Rc<usize>,
    req_rx: mpsc::UnboundedReceiver<UringRequest>,
}

impl Uring {
    async fn run(mut self) {
        LocalSet::new()
            .run_until(async move {
                while let Some(req) = self.req_rx.recv().await {
                    // do some thing
                    req.tx.send(UringResponse {}).unwrap();
                }
            })
            .await;
    }
}

pub struct App {
    uring_tx: mpsc::UnboundedSender<UringRequest>,
}

impl App {
    pub fn run(self) {
        // tokio::spawn(uring.run());
    }

    pub async fn foo(&self) -> UringResponse {
        let (tx, rx) = oneshot::channel();
        let req = UringRequest { tx };
        self.uring_tx.send(req).unwrap();
        rx.await.unwrap()
    }
}
```
You can see, `Uring` is `!Send` and `!Sync`, but `App` is `Send` and `Sync`. So `App` can be used in tokio's multi-thread runtime.

**Comment by silence-coding** [comment]
I've tried using channel for file read and write collaboration between tokio-uring and tokio's multi-thread runtimes, but the performance is no better than tokio::fs.

**Comment by songzhi** [comment]
@silence-coding You should do some profiling to make sure which part is the bottleneck.

**Comment by silence-coding** [comment]
@songzhi OK, I'd like to ask if tokio-uring has any plans to switch to multi-thread mode? Or when will it be released as a future of tokio
