### ISSUE TITLE
Runtime will not start

### ISSUE THREAD

**Issue by sempervictus** [tokio-rs/tokio-uring#49]
I tried switching my application to using this lib for the primary reactor as shown in the example, but on startup it produces:
```rust
 thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 38, kind: Unsupported, message: "Function not implemented" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-uring-0.1.0/src/lib.rs:131:42
```
Build target is MUSL, using `clux/muslrust`  as a base container for the build.
Execution environment is Arch Linux, happens with liburing installed and without, liburing is:
```
Name            : liburing
Version         : 2.0-1
Description     : Linux-native io_uring I/O access library
Architecture    : x86_64
URL             : https://git.kernel.dk/cgit/liburing/
Licenses        : LGPL2.1  MIT
Groups          : None
Provides        : liburing.so=2-64
Depends On      : glibc
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 74.58 KiB
Packager        : David Runge <dvzrv@archlinux.org>
Build Date      : Thu 11 Mar 2021 09:08:44 PM UTC
Install Date    : Fri 20 Aug 2021 10:28:32 PM UTC
Install Reason  : Explicitly installed
Install Script  : No
```

**Comment by KerfuffleV2** [comment]
@sempervictus According to the README, `tokio-uring` only supports the one `tokio_uring::fs::File` resource type that it provides. Just switching reactors to this when your application is using other types of resources wouldn't be expected to work.

It's been a while but I'm assuming you didn't already figure this out as the issue is still open.

**Comment by Noah-Kennedy** [comment]
@sempervictus did that answer your question?

**Comment by autumnontape** [comment]
I haven't encountered this issue, but I'm confused. The readme says that tokio-uring is compatible with Tokio and that "Any library that works with Tokio also works with tokio-uring," and switching a Tokio-based project of mine to run on a tokio-uring runtime without changing any other part of the code does work. Is there some other way of mixing tokio and tokio-uring that isn't supported?

**Comment by Noah-Kennedy** [comment]
@autumnontape That case will always work, unless you used `block_in_place`. What doesn't work is trying to use tokio-uring stuff within the normal tokio runtime (using `#[tokio::main]`).

**Comment by Noah-Kennedy** [comment]
@sempervictus is this issue ongoing?

**Comment by sempervictus** [comment]
Pardon, have not been using the library in recent efforts, closing.
