### ISSUE TITLE
Test failure: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }

### ISSUE THREAD

**Issue by tkaitchuck** [tokio-rs/tokio-uring#59]
Upon checking out the code and running `cargo test` I observe:
```
---- too_many_submissions stdout ----
thread 'too_many_submissions' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }', tests/driver.rs:84:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- complete_ops_on_drop stdout ----
thread 'complete_ops_on_drop' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }', tests/driver.rs:53:56

```

**Comment by Noah-Kennedy** [comment]
I'm getting this from 5.14

**Comment by carllerche** [comment]
Interesting. I am seeing that as well now. My guess there was a change in kernel behavior.

**Comment by BraulioVM** [comment]
I believe it's not related to a change in kernel behaviour. I believe it's related to https://github.com/rust-lang/rust/pull/85746 . Some of the logic in this crate depends on `io::ErrorKind::Other`, which we may not be getting from upstream libraries (std or otherwise)  anymore.
