### ISSUE TITLE
Allow access for Runtime struct?

### ISSUE THREAD

**Issue by ileixe** [tokio-rs/tokio-uring#91]
Hi

I'm trying to benchmark tokio-uring and different implementations. As criterion [requires Runtime struct](https://bheisler.github.io/criterion.rs/book/user_guide/benchmarking_async.html) to run async code, I'd like to ask for changing Runtime struct visibility.

Is it valid change or any other viable solution to achieve it?

Thanks

**Comment by ileixe** [comment]
I just found recent PR(https://github.com/tokio-rs/tokio-uring/pull/88) to achieve it.

**Comment by nik9000** [comment]
I think it might be useful to constrain this issue to something like "make tokio-uring work with criterion" - whatever makes that work is fine by me, at least. Does anyone have any other reasons for referencing the `Runtime` struct?

**Comment by Noah-Kennedy** [comment]
For an API, I think it should look like the normal tokio runtime API, except with only `spawn`, `block_on`, `new`, and `spawn_blocking`. We can add a handle as well, either here or later.

**Comment by nik9000** [comment]
So you are thinking of making the struct public with public implementations with the same signature as those methods? I might be able to have a look in the next few days. Or, if you want it, please go ahead. I don't know what I'm doing and I don't get in the way.

**Comment by nik9000** [comment]
When I pull this locally I get a few test failures randomly - `explicit_close` and `drop_off_runtime` and sometimes the tests hang around the same place. Is that normal?

**Comment by Noah-Kennedy** [comment]
What kernel do you have?

**Comment by nik9000** [comment]
```
Linux porco 5.19.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 29 Aug 2022 15:51:05 +0000 x86_64 GNU/Linux
```

**Comment by Noah-Kennedy** [comment]
@nik9000 see #119.

**Comment by FrankReh** [comment]
> When I pull this locally I get a few test failures randomly - `explicit_close` and `drop_off_runtime` and sometimes the tests hang around the same place. Is that normal?

As you indicated in #119, that problem from Sep seems fixed.

**Comment by FrankReh** [comment]
I'm glad the question of a handle came up in this thread already.
