### ISSUE TITLE
JoinHandle not completing when too many tasks or opened files present

### ISSUE THREAD

**Issue by FrankReh** [tokio-rs/tokio-uring#93]
Hi, probably I'm doing something wrong while trying the 0.3.0 tokio_uring.

I build a release from the small benchmark code sample in #35 and run it on a cloud Clear Linux OS with a kernel at 5.18.9 but only see it complete successfully when a maximum of 512 urandom tasks are spawned before awaiting each of their handles. When I run with the original 1000 tasks, usually the 513th handle.await.unwrap() doesn't return. The 'ulimit -n' had been 1024 so I changed that to 2048 and it may have made a small difference. Sometimes a few more task handles complete. And when I add print statements, the entire benchmark sometimes runs, sometimes still hangs.

I understand the task/code that is being benchmarked is almost throwaway code, there are no explicit checks for errors, it opens /dev/urandom, reads 10 bytes, closes it, opens /dev/null, writes the 10 bytes, and closes it. But I'm under the impression each task should still complete if any of the steps failed.

I don't think it's as relevant, but just in case, I'll add that I'm cross compiling from Darwin with the _x86_64-unknown-linux-musl_ target and it is being run on a single vCPU machine running Clear Linux OS. And it's no surprise that the cpu is pegged at 100% utilization until the hang.

Is it obvious that I'm doing something wrong or is there an avenue I can follow to debug this further?

Here is the code again.
```rust
const HCOUNT : usize = 1_000;
// const HCOUNT : usize = 512;
// const HCOUNT : usize = 800;

const DEBUG : bool = false;

async fn compute_tokio_uring() {
    use tokio::task::JoinHandle;
    use tokio_uring::fs::File;

    let handles: Vec<JoinHandle<_>> = (0..HCOUNT)
        .map(|_| {
            tokio_uring::spawn(async {
                let buffer = vec![0; 10];
                let dev_urandom = File::open("/dev/urandom").await.unwrap();
                let (res, buffer) = dev_urandom.read_at(buffer, 0).await;
                let _read_n = res.unwrap();
                let _ = dev_urandom.close().await;
                let dev_null = File::open("/dev/null").await.unwrap();
                let _ = dev_null.write_at(buffer, 0).await;
                let _ = dev_null.close().await;
            })
        })
        .collect();
    if DEBUG {
        println!("A");
    }
    let mut count = 0;
    for handle in handles {
        if DEBUG {
            println!("B count {}", count);
        }
        count += 1;
        handle.await.unwrap();  // <--- This is the line that appears to hang, often on the 513th invocation.
    }
    if DEBUG {
        println!("C");
    }
}

fn main() {
    tokio_uring::start(async {
        for _ in 0..10 {
            compute_tokio_uring().await;
        }
        for _ in 0..3 {
            let before = std::time::Instant::now();
            for _ in 0..1_000 {
                compute_tokio_uring().await;
            }
            let elapsed = before.elapsed();
            println!(
                "[tokio_uring] {:?} total, {:?} avg per iteration",
                elapsed,
                elapsed / 1_000
            );
        }
    })
}
```

**Comment by Noah-Kennedy** [comment]
You've hit an issue I found while fixing something else months ago, decided I would fix the next day, and then promptly forgot about until now lmao.

`io_uring` has an unfortunate footgun where you can put more events in-flight than the completion queue can hold, thus allowing you to overflow the queue. If the queue overflows, the extra completions are yeeted into the void, never to be received.

The solution here is to add a semaphore to make sure we can't put more events in-flight than the cqueue can hold.

**Comment by Noah-Kennedy** [comment]
I'll get a fix up in a bit.

**Comment by Darksonn** [comment]
Huh? My understanding is that this was true in the first versions of the driver, but hasn't this been fixed? As far as I know, the driver should hold on to completions that don't fit until you empty the completion queue.

**Comment by Noah-Kennedy** [comment]
@FrankReh I will need to look at this, but I agree that this sounds like a _much_ better option!

**Comment by ollie-etl** [comment]
@FrankReh I think i've hit this too - I will also take a look

**Comment by FrankReh** [comment]
I think I saw the problem fixed locally by using the CQ_OVERFLOW bit to say when tick should be run again. But I was waiting for the Rc/RefCell driver rework. My solution had tick to using a loop and checking the squeue bit itself for deciding when to run again. I wasn't thrilled with the memory sync options that were available and saw a recent PR for io-uring that would have separated read and write fences but it wasn't accepted yet.

The Rc removal hasn't been committed yet. And I wanted to see if the RefCell couldn't be pushed further down so tick didn't need to be given a mutable driver either.

Not to say you shouldn't look at the problem. Maybe you'll find a better way.

**Comment by Noah-Kennedy** [comment]
Let's go with your approach once the rt changes get committed.

**Comment by FrankReh** [comment]
This has been solved. Waiting for https://github.com/tokio-rs/io-uring/pull/152 or its equivalent to be merged and then this crate's version for io-uring to be bumped appropriately.
