### ISSUE TITLE
How many system calls happen underneath if I were to broadcast to bunch of connected clients of my server?

### ISSUE THREAD

**Issue by kant777** [tokio-rs/tokio-uring#95]
I am new to this library and I am trying to figure out how does this library help batching syscalls for network I/O. my use case is I am trying to use this library to broadcast a stream of messages m1,m2, m3....to all the connected sockets of my server. so if there are 1000 clients connected to my server I want to broadcast each message to all 1000 and I am trying to accomplish this is in as few syscalls as possible because called syscall.send on every socket descriptor seems to be the bottleneck of my server to scale. Latency is very important for my app.

Below are my questions/comments about rio library

does calling ring.write_at makes a syscall? I am assuming the answer is no since it returns a Future however I assume calling ring.write_at.await? will make a syscall. so if I need to batch I need to call ring.write_at for each individual message I want to broadcast and add then call ring.submit_all? but then what I do with each each individual future I get from calling ring.write_at?
How do I handle backpressure in my app if the submission queue is full? what I do? just keep retrying forever?

**Comment by Noah-Kennedy** [comment]
This is `tokio-uring`, not `rio`. If you have a question about this, I'm happy to answer it, but I am not familiar with the implementation details of `rio`.

**Comment by kant777** [comment]
@Noah-Kennedy Sorry, it was a copy/paste error and I haven't got any response from `rio` so my questions are generally the same and I slightly edited. would be great to know how tokio-uring can help? hope my question is generic enough if not please let me know

**Comment by Noah-Kennedy** [comment]
So, IO functions/methods in `tokio-uring` will push a SQE to the submission queue. In current releases, these operations are immediately submitted to the kernel, resulting in a syscall. On the master branch, we have implemented batching, and thus we will submit all operations in the queue if it becomes full when constructing an op, and will also submit all operations to the kernel before parking, so system calls tend to be pretty efficiently amortized across operations.

I'd also like to get hooks into tokio at some point to allow us to submit operations periodically when tokio runs it's internal maintenance routine.

**Comment by kant777** [comment]
@Noah-Kennedy Got it, so I need to use master, because if it submits a syscall for every operation then that defeats the purpose of io_uring altogether. I am glad to hear that batching is implemented internally but does it submit to kernel only when the buffer is full? what if the buffer isn't full? is there any timer? if not, then why not let users batch their syscalls and provide a function like `submit_all`?

**Comment by Noah-Kennedy** [comment]
If we attempt to push an operation but the buffer is full, we submit all operations in the buffer to make space and then push.

There is no timer for periodic dispatch. This is better implemented by hooking into the maintenance loop of tokio.

Allowing users to control their own batching is something I'd like to get implemented soon, alongside some newer APIs that give more fine-grained control of operation submission.

**Comment by kant777** [comment]
Got it, But again what if the buffer isn't full? it will stay in queue forever? I didn't mean to say timer in isolation but a combination of buffer size and the timer or let the user take care of it all!

**Comment by Noah-Kennedy** [comment]
Currently on master, when there isn't work to do (ie the system parks), it will flush the squeue and submit. This isn't released yet because this isn't exactly ideal; we need to get hooks into tokio to periodically flush the queue every X task polls (I forget how often the tokio maintenance loop runs).
